import clsx from 'clsx'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es">
      <body className={clsx(inter.className, 'p-10')}>
        <header className="py-7">
          <h1 className="text-lg ">
            Welcome Back,{' '}
            <strong className="tracking-wider text-black/80 font-extrabold ">
              let´s Find Your Job! 🔥
            </strong>
          </h1>
        </header>

        {children}
      </body>
    </html>
  )
}
